log:
  date:
    show: "false"
  debug: "false"
  syslog:
    enabled: "true"
mode: iptables
net:
  interface:
    name: ens170
  ipv6:
    end: 2001:0df3:2e80:bfff:ffff:ffff:ffff:ffff
    start: '2001:df3:2e80:4000::'
netflix:
  title: "70143836"