net:
  ipv6:
    start: '2001:df3:2e80:4000::'
    end: '2001:df3:2e80:4000:ffff:ffff:ffff:ffff'
  interface: 'ens170'

mode: 'iptables'

netfilx:
  title: '70143836'

log:
  debug: true
  date:
    show: true